import io.github.besi97.graphql.codegen.gradle.GraphQLCodegenGradleTask

plugins {
    id "java"
    id "idea"
    id "application"

    // use the latest available version:
    // https://plugins.gradle.org/plugin/io.github.besi97.graphql.codegen
    id "io.github.besi97.graphql.codegen" version "6.2.1-SNAPSHOT"
}

application {
    mainClass = "io.github.besi97.order.Application"
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web:4.1.1"
    implementation "org.springframework.boot:spring-boot-starter-data-mongodb:4.1.1"

    implementation "com.graphql-java-kickstart:graphql-spring-boot-starter:15.1.0"
    implementation "com.graphql-java-kickstart:graphiql-spring-boot-starter:11.1.0"
    implementation "com.graphql-java:graphql-java-extended-scalars:24.0"

    // use the latest available version:
    // https://search.maven.org/artifact/io.github.besi97/graphql-java-codegen
    implementation "io.github.besi97:graphql-java-codegen:6.2.1-SNAPSHOT"

    implementation "org.apache.httpcomponents:httpclient:4.5.14"
    implementation "javax.validation:validation-api:2.0.1.Final"

    implementation "org.mapstruct:mapstruct:1.6.3"
    annotationProcessor "org.mapstruct:mapstruct-processor:1.6.3"

    compileOnly "org.projectlombok:lombok:1.18.46"
    annotationProcessor "org.projectlombok:lombok:1.18.46"
}


/**
 * Generate requests and model from external service
 */
compileJava.dependsOn "graphqlCodegenProductService"
sourceSets.main.java.srcDir "$buildDir/generated-client"
task graphqlCodegenProductService(type: GraphQLCodegenGradleTask) {
    graphqlSchemas.includePattern = "schema-product-service\\.graphqls"
    outputDir = new File("$buildDir/generated-client")
    modelPackageName = "io.github.besi97.product.graphql.model"
    customTypesMapping = [
            DateTime: "java.util.Date"
    ]
    modelNameSuffix = "TO"
    generateApis = false
    generateClient = true
    generateParameterizedFieldsResolvers = false
}


/**
 * Generate apis and model
 */
compileJava.dependsOn "graphqlCodegenOrderService"
sourceSets.main.java.srcDir "$buildDir/generated-server"
task graphqlCodegenOrderService(type: GraphQLCodegenGradleTask) {
    graphqlSchemas.includePattern = "schema\\.graphqls"
    outputDir = new File("$buildDir/generated-server")
    apiPackageName = "io.github.besi97.order.graphql.api"
    modelPackageName = "io.github.besi97.order.graphql.model"
    customTypesMapping = [
            DateTime: "java.util.Date"
    ]
    modelNameSuffix = "TO"
}

/**
 * Generate requests and model from another external service
 */
compileJava.dependsOn "graphqlCodegenStarwarsService"
sourceSets.main.java.srcDir "$buildDir/generated-client-starwars"
task graphqlCodegenStarwarsService(type: GraphQLCodegenGradleTask) {
    graphqlSchemas.includePattern = "schema-starwars-service\\.graphqls"
    outputDir = new File("$buildDir/generated-client-starwars")
    packageName = "io.github.besi97.starwars.graphql"
    customAnnotationsMapping = [
            "Character": [
                    "@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, property = \"__typename\")",
                    "@com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver(io.github.besi97.order.external.starwars.CharacterTypeResolver.class)"
            ]
    ]
    generateClient = true
    generateApis = false
    generateBuilder = true
    generateToString = true
    generateParameterizedFieldsResolvers = false
}


repositories {
    mavenCentral()
    mavenLocal()
}


